version: '3.7'

services:
  lb:
    image: nginx:1.21
    container_name: load-balancer-container
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/certs/macro.dev+1.pem:/etc/nginx/certs/app-cert.pem:ro
      - ./nginx/certs/macro.dev+1-key.pem:/etc/nginx/certs/app-cert-key.pem:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - macro-st-administration
      - macro-st-authserver
      - macro-st-identity
      - macro-st-projects
      - macro-st-saas
      - macro-st-web
      - macro-st-public-web
      - macro-st-gateway-web
    restart: on-failure
    networks:
      - macro-network

  macro-st-administration:
    image: macro/service-administration:latest
    container_name: administration-service-container
    build:
      context: ../../
      dockerfile: services/administration/host/Macro.AdministrationService.HttpApi.Host/Dockerfile
    environment:
      # - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - App__SelfUrl=https://macro-st-administration
      - App__CorsOrigins=https://gateway-st-web,gateway-st-web-public
      - RemoteServices__AbpIdentity__BaseUrl=macro-st-identity
      - RemoteServices__AbpIdentity__UseCurrentAccessToken=false
      - ConnectionStrings__AdministrationService=User ID=postgres;Password=myPassw0rd;Host=postgres-db;Port=5432;Database=AdministrationService;Pooling=false;
      - ConnectionStrings__IdentityService=User ID=postgres;Password=myPassw0rd;Host=postgres-db;Port=5432;Database=IdentityService;Pooling=false;
      - ConnectionStrings__SaasService=User ID=postgres;Password=myPassw0rd;Host=postgres-db;Port=5432;Database=SaasService;Pooling=false;
      - AuthServer__Authority=http://macro-st-authserver
      - AuthServer__RequireHttpsMetadata=false
      - IdentityClients__Default__Authority=http://macro-st-identity
      - Redis__Configuration=redis
      - RabbitMQ__Connections__Default__HostName=rabbitmq
    depends_on:
      redis:
        condition: service_healthy
      postgres-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    networks: 
      - macro-network
  macro-st-identity:
    image: macro/service-identity:latest
    container_name: identity-service-container
    build:
      context: ../../
      dockerfile: services/identity/host/Macro.IdentityService.HttpApi.Host/Dockerfile
    environment:
      # - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - App__SelfUrl=https://macro-st-identity
      - App__CorsOrigins=https://gateway-st-web,gateway-st-web-public
      - AuthServer__Authority=http://macro-st-authserver
      - AuthServer__RequireHttpsMetadata=false
      - ConnectionStrings__AdministrationService=User ID=postgres;Password=myPassw0rd;Host=postgres-db;Port=5432;Database=AdministrationService;Pooling=false;
      - ConnectionStrings__IdentityService=User ID=postgres;Password=myPassw0rd;Host=postgres-db;Port=5432;Database=IdentityService;Pooling=false;
      - ConnectionStrings__SaasService=User ID=postgres;Password=myPassw0rd;Host=postgres-db;Port=5432;Database=SaasService;Pooling=false;
      - Redis__Configuration=redis
      - RabbitMQ__Connections__Default__HostName=rabbitmq
      - IdentityServerClients__Web__RootUrl=https://macro-st-web
      - IdentityServerClients__PublicWeb__RootUrl=https://macro-st-public-web
      - IdentityServerClients__WebGateway__RootUrl=https://macro-st-gateway-web
      - IdentityServerClients__PublicWebGateway__RootUrl=https://macro-st-gateway-web
      - IdentityServerClients__IdentityService__RootUrl=https://macro-st-identity
      - IdentityServerClients__AdministrationService__RootUrl=https://macro-st-administration
      - IdentityServerClients__AccountService__RootUrl=https://macro-st-authserver
    depends_on:
      redis:
        condition: service_healthy
      postgres-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    networks: 
      - macro-network
  macro-st-projects:
    image: macro/service-project:latest
    container_name: project-service-container
    build:
      context: ../../
      dockerfile: services/projects/host/Macro.Projects.HttpApi.Host/Dockerfile
    environment:
      # - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80;http://+:81;
      - App__SelfUrl=https://macro-st-projects
      - App__CorsOrigins=https://macro-st-gateway-web,https://macro-st-gateway-web,https://macro-st-public-web,https://macro-st-web
      - AuthServer__Authority=http://macro-st-authserver
      - AuthServer__RequireHttpsMetadata=false
      - Kestrel__EndPoints__Http__Url=http://docker.host.internal:80
      - Kestrel__EndPoints__gRPC__Url=http://docker.host.internal:81
      - Kestrel__EndPoints__gRPC__Protocols=Http2
      - ConnectionStrings__AdministrationService=User ID=postgres;Password=myPassw0rd;Host=postgres-db;Port=5432;Database=AdministrationService;Pooling=false;
      - ConnectionStrings__IdentityService=User ID=postgres;Password=myPassw0rd;Host=postgres-db;Port=5432;Database=IdentityService;Pooling=false;
      - ConnectionStrings__SaasService=User ID=postgres;Password=myPassw0rd;Host=postgres-db;Port=5432;Database=SaasService;Pooling=false;
      - Redis__Configuration=redis
      - RabbitMQ__Connections__Default__HostName=rabbitmq
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure  
    networks: 
      - macro-network
  macro-st-saas:
    image: macro/service-saas:latest
    container_name: saas-service-container
    build:
      context: ../../
      dockerfile: services/saas/host/Macro.SaaS.HttpApi.Host/Dockerfile
    environment:
      # - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - App__SelfUrl=https://macro-st-saas
      - App__CorsOrigins=https://macro-st-gateway-web,https://macro-st-gateway-web,https://macro-st-public-web
      - ConnectionStrings__AdministrationService=User ID=postgres;Password=myPassw0rd;Host=postgres-db;Port=5432;Database=AdministrationService;Pooling=false;
      - ConnectionStrings__IdentityService=User ID=postgres;Password=myPassw0rd;Host=postgres-db;Port=5432;Database=IdentityService;Pooling=false;
      - ConnectionStrings__SaasService=User ID=postgres;Password=myPassw0rd;Host=postgres-db;Port=5432;Database=SaasService;Pooling=false;
      - AuthServer__Authority=http://macro-st-authserver
      - AuthServer__RequireHttpsMetadata=false
      - Redis__Configuration=redis
      - RabbitMQ__Connections__Default__HostName=rabbitmq    
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure  
    networks: 
      - macro-network
 
  macro-st-authserver:
    image: macro/app-authserver:latest
    container_name: app-authserver-container
    build:
      context: ../../
      dockerfile: apps/Macro.AuthServer/Dockerfile
    environment:
      # - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80;
      - App__SelfUrl=https://macro-st-authserver
      - App__CorsOrigins=https://macro-st-web,https://macro-st-public-web,https://macro-st-identity,http://macro-st-administration,https://macro-st-administration
      - App__RedirectAllowedUrls=http://macro-st-web
      - AuthServer__Authority=http://macro-st-authserver
      - AuthServer__RequireHttpsMetadata=false
      - ConnectionStrings__AdministrationService=User ID=postgres;Password=myPassw0rd;Host=postgres-db;Port=5432;Database=AdministrationService;Pooling=false;
      - ConnectionStrings__IdentityService=User ID=postgres;Password=myPassw0rd;Host=postgres-db;Port=5432;Database=IdentityService;Pooling=false;
      - ConnectionStrings__SaasService=User ID=postgres;Password=myPassw0rd;Host=postgres-db;Port=5432;Database=SaasService;Pooling=false;
      - Redis__Configuration=redis
      - RabbitMQ__Connections__Default__HostName=rabbitmq
    depends_on:
      redis:
        condition: service_healthy
      postgres-db:
        condition: service_healthy  
      rabbitmq:
        condition: service_healthy
    restart: on-failure  
    networks: 
      - macro-network
  macro-st-web:
    image: macro/app-web:latest
    container_name: app-web-container
    build:
      context: ../../
      dockerfile: apps/angular/Dockerfile
    volumes:
      - ./nginx/dynamic-env.json:/usr/share/nginx/html/dynamic-env.json
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    networks: 
      - macro-network
  macro-st-public-web:
    image: macro/app-publicweb:latest
    container_name: app-publicweb-container
    build:
      context: ../../
      dockerfile: apps/Macro.Blazor.Server/Dockerfile
    environment:
      # - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80;
      - App__SelfUrl=https://macro-st-public-web
      - AuthServer__Authority=http://macro-st-authserver
      - AuthServer__RequireHttpsMetadata=false
      - RemoteServices__Default__BaseUrl=http://macro-st-gateway-web/                
      - Redis__Configuration=redis
      - RabbitMQ__Connections__Default__HostName=rabbitmq
      - ReverseProxy__Clusters__cluster1__Destinations__destination1__Address=http://macro-st-gateway-web
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure  
    networks: 
      - macro-network
  macro-st-gateway-web:
    image: macro/gateway-web:latest
    container_name: gateway-web-container
    build:
      context: ../../
      dockerfile: gateway/Macro.Gateway/Dockerfile
    environment:
      #- ASPNETCORE_ENVIRONMENT=Docker # Yarp can't resolve dns, needs to be overridden
      - ASPNETCORE_URLS=http://+:80;
      - App__SelfUrl=https://macro-st-gateway-web
      - App__CorsOrigins=https://macro-st-web
      - AuthServer__Authority=http://macro-st-authserver
      - AuthServer__RequireHttpsMetadata=false
      - Redis__Configuration=redis
      - ReverseProxy__Clusters__accountCluster__Destinations__destination1__Address=http://macro-st-authserver
      - ReverseProxy__Clusters__identityCluster__Destinations__destination1__Address=http://macro-st-identity
      - ReverseProxy__Clusters__administrationCluster__Destinations__destination1__Address=http://macro-st-administration
      - ReverseProxy__Clusters__feature-management-cluster__Destinations__destination1__Address=http://macro-st-administration
      - ReverseProxy__Clusters__permission-management-cluster__Destinations__destination1__Address=http://macro-st-administration
      - ReverseProxy__Clusters__setting-management-cluster__Destinations__destination1__Address=http://macro-st-administration
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure  
    networks: 
      - macro-network

networks:
  macro-network:
    external: true
